### ISSUE TITLE
chicken spawns depend on previous chick positions and can be manipulated

### ISSUE THREAD

**Issue by dallmeyer** [my-opengoal-mods/OG-Jak-The-Chicken-Reborn#43]
Easy place to see this is during Villa Cube ILs. In a full-game run / if you don't manip it, the first chick behind the warp gate often takes several seconds to go in and for autosave to kick in, preventing you from picking up the other chicks.

But if you grab a chick but reset the IL before you return it to the portal, when you grab the chick behind the warp gate it goes in very quickly and autosaves early, without preventing pickup of other chicks. I do it in my IL run here - https://www.youtube.com/watch?v=Kx5ubw8KMVQ

**Comment by Zedb0T** [comment]
Fixed by https://github.com/my-opengoal-mods/OG-Jak-The-Chicken-Reborn/tree/rewrite3-3subtest
