### ISSUE TITLE
Camera on some warp continue points makes it hard to verify first frame jak touches the ground

### ISSUE THREAD

**Issue by dallmeyer** [my-opengoal-mods/OG-Jak-The-Chicken-Reborn#44]
sometimes the camera is behind the portal, and the particle effects make it hard to see jak. in other cases jak is just off screen (glass towers) depending on how you rotate the camera

kinda solved by https://github.com/OpenGOAL-Mods/OG-Mod-Base/pull/103

but maybe a couple of the camera angles could still be improved in any case (pyramid, glass towers come to mind)

**Comment by Zedb0T** [comment]
Yeah fixed by https://github.com/OpenGOAL-Mods/OG-Mod-Base/pull/103
I actually am a HUGE fan of the pyramid/glass tower continue points, it feels really immersive when the camera goes through the portal like you just came out of it yourself.
